a=input('Enter first Number : ')
b=input('Enter second Number : ')
print("a+b",int(a)+int(b))
print("a-b",int(a)-int(b))
print("a*b",int(a)*int(b))
print("a/b",int(a)/int(b))
print("a%b",int(a)%int(b))
print("a//b",int(a)//int(b))
print('a**b',int(a)**int(b))